### ISSUE TITLE
shreyabadve35 Find the CGPA and SGPA

### ISSUE THREAD

**Issue by ombharamadev** [ombharamadev/data-project-1#2]

**Comment by ombharamadev** [comment]
you need to add title in csv output file file_name,cgpa,scgpa.... update it
![image](https://github.com/ombharamadev/data-project-1/assets/150242178/e40a5b34-8e1c-47d9-b287-fa2956dbcfea)

**Comment by Apollo-bot35** [comment]
done 
<img width="959" alt="img2" src="https://github.com/ombharamadev/data-project-1/assets/71018084/b7d0d52b-1f0d-42ce-9b35-284c93fa9b0e">
